### ISSUE TITLE
Create Steering Wheel Button Mapper

### ISSUE THREAD

**Issue by seanavery** [seanavery/g29-py#1]
## Description
Currently, the driver only supports steering wheel and pedals. Time to add the buttons.

## Todo
- [x] Reverse engineer button axis by comparing byte array query from previous cache.
- [x] Reverse button values from bytes.
- [x] Add buttton scaffold to state.
- [x] Add button setters to state update thread.

**Comment by seanavery** [comment]
## Axis

The byte array returned from the g29 is 8 bytes.

```
BUTTON_PADS = 0
BUTTON_MISC = 1
BUTTON_PLUS = 2
BUTTON_MINUS = 3
STEERING_COARSE = 4
STEERING_FINE = 5
PEDAL_ACCELERATOR = 6
PEDAL_BRAKE = 7
PEDAL_CLUTCH = 8
```

**Comment by seanavery** [comment]
## GAME PAD
GAME_PAD_NIL = 8

GAME_PAD_UP = 0
GAME_PAD_DOWN = 4
GAME_PAD_RIGHT = 2
GAME_PAD_LEFT = 6

GAME_PAD_X = 24
GAME_PAD_SQUARE = 40
GAME_PAD_CIRCLE = 72
GAME_PAD_TRIANGLE = 136

**Comment by seanavery** [comment]
##  Misc
```
MISC_NIL = 0
MISC_R2 = 4
MISC_R3 = 64
MISC_L2 = 8
MISC_L3 = 128
MISC_SHARE = 16
MISC_OPTIONS = 32
```

**Comment by seanavery** [comment]
## MIsc2
```
MISC2_TRACK_RIGHT = 2
MISC2_TRACK_LEFT = 4
MISC2_BACK = 8
MISC2_MINUS = 1
MISC_PSTATION = 16
```

**Comment by seanavery** [comment]
## State

- [ ] Look into how pygame is returning these values
